export const GET_HIRE_LIST = "GET_HIRE_LIST";
export const GET_APPROVAL_JOINEE = "GET_APPROVAL_JOINEE";
export const ADD_HIRE = "ADD_HIRE";
export const APPROVED_REQUEST = "APPROVED_REQUEST";
export const REJECTED_REQUEST = "REJECTED_REQUEST";

export const CLEAR_APPROVAL_JOINEE = "CLEAR_APPROVAL_JOINEE";
export const CLEAR_ADD_HIRE = "CLEAR_ADD_HIRE";
export const CLEAR_APPROVED_DATA = "CLEAR_APPROVED_DATA";
export const CLEAR_REJECTED_DATA = "CLEAR_REJECTED_DATA";
