export const employeeList  = {
        manager: 
        [
                "Vidhi Maheshwari", 
                "Ankit Shekhawat",
                "Kumar Rishi Anand",
                "B Elango",
                "Sunil Fernandes",
                "Aditya Agarwal",
                "Rubel Chowdhury",
                "Suprita S Totagi",
                "Trinanjan Saha",
                "Saurav Dutta",
                "Shreyas Kumar",
                "Dhanush S Shetty",
                "Ganapati Dattatraya Hegde",
                "Abhishek P",
                "Dimple Patel",
                "Ramanjaneya Reddy D",
                "Heman K S",
                "Ayush Jaiswal",
                "Sujay S",
                "Unnikrishnan S V",
                "Sreekumar Paramu",
                "Gaurav Kumar Verma",
                "Varun Malyala",
                "Akash A",
                "M Sunilkumar",
                "Sunil Kumar G",
                "Ankita Singh",
                "Shaili Srivaava",
                "Rajat Shah",
                "Manoj Sah",
                "Dommeti Chiranjeevi Saiteja",
                "Ananya Tripathi",
                "Prasad Hegde",
                "Swati Shreya",
                "Priyanka Mahour",
                "Subramanya G S",
                "Ritesh Ghosh",
                "Shilpy Parashar",
                "Kiran Kumar C K",
                "Abhishek Panicker",
                "Neelabh Dutta",
                "Varnika Sharma",
                "Raksha R",
                "Ravi Kundalia",
                "Kypa",
                "Adarsh Sharma",
                "Akshata Ambi",
                "Kritish",
                "Gagan Karvulo",
                "Wasif",
                "Bhima Shankar Sutar",
                "Atul Sharan Raj",
                "Paras Agrawal",
                "Chethan Shankar",
                "Guruprasad Shetty",
                "Nitish Mehta",
                "Shreevathsa S Chatra",
                "Dipesh Agarwal",
                "Tegbir Singh",
                "Nitish Bhaskar",
                "Subramanya Aadiga",
                "Selva",
                "Tejasvi H S",
                "Bharath T S"


        ],
        location : [
                "Bangalore",
                "Seatle"
        ]
}
      
      export default {
        employeeList,
      }